DROP DATABASE STORE;

CREATE DATABASE STORE;

USE STORE;

CREATE TABLE urls(
ID INT AUTO_INCREMENT,
ORIGIN_URL VARCHAR(100) NOT NULL,
constraint ID primary key (ID)
);

ALTER TABLE urls AUTO_INCREMENT=1001;